### ISSUE TITLE
关于流程的一个小建议

### ISSUE THREAD

**Issue by Cathon** [LCTT/lctt-cli#1]
挑选筛选结果的时候，可以在每一篇未翻译的文章前（或后）添加序号。
然后用户输入序号，确认，进入下一步。

**Comment by erlinux** [comment]
收到，完成优化问题后。

GetNewOne 会实现去这个 idea ~

**Comment by vizv** [comment]
scheduled

**Comment by erlinux** [comment]
**流程建议实现中...**

按照[项目规划](https://github.com/LCTT/lctt-cli/blob/master/others/images/%E9%A1%B9%E7%9B%AE%E8%A7%84%E5%88%92.png)当前已经完成项目重构，相较于v1版本，v2版本代码美观、易读、并具有v3级重构能力。

针对 "用户输入序号" ，我准备试试使用数组实现。

**Comment by erlinux** [comment]
**流程建议已实现**

后续将进入审查，优化阶段。**感谢！**
