### ISSUE TITLE
find / -iname TranslateProject搜索过慢的问题。

### ISSUE THREAD

**Issue by leemeans** [LCTT/lctt-cli#16]
在options/list/list.sh中有这样一句
export LCTT=$(find / -iname TranslateProject 2>/dev/null |\   9   awk -F "TranslateProject"IGNORECASE=1 '{print $1}')
其中find -iname 命令将会在整个系统中搜索所有包含TranslateProject的路径，导致执行时每次都要遍历所有目录，速度很慢。

**Comment by leemeans** [comment]
可以使用locate --basename或者增加命令行选项指定工程所在目录，这样会快很多

**Comment by erlinux** [comment]
收到，将做代码更改。

**Comment by erlinux** [comment]
已收到并合并你的代码更改，因为该代码位于WSL出现不兼容。故合并至 #22 ISSUE 统一处理。
