### ISSUE TITLE
我发现一个问题，使用了mlocate的方法以后WSL就不能用了。

### ISSUE THREAD

**Issue by erlinux** [LCTT/lctt-cli#22]
当然，在之前使用 find 的情况下，速度也是感人。

需要修复 mlocate 位于 Windows Subsystem for Linux 的使用。

**Comment by lujun9972** [comment]
或者find完了之后，把结果写到缓存文件里？

**Comment by leemeans** [comment]
我觉得可以这样做：启用一个新的命令行选项，比如-usemlocate -usefind这种，这样代码就有两个分支，按照不同的选项赋值的变量选择使用locate 和find来查找。还可以指定路径，加入-setprojectpath 这种选项来设置。你们觉得呢？

**Comment by leemeans** [comment]
写入缓存怎么写呢？

**Comment by lujun9972** [comment]
随便找个文件把找到的路径写进去就行了，下一次先从文件里读路径，读失败了或者路径失效了才去find

**Comment by erlinux** [comment]
因为已经合并 @leemeans  采用的 `locate` 方法，我的想法是准备这么做。打算做个判断，如果发现`locate` 找不到或者找到的文件不是最新，那么就调用 `find` 进行查询。用户可以使用俩种方法，以提供项目搜索速度。第一种是可以基于命令 `-d ` 参数后跟项目位置，或类似 @lujun9972 所说直接读取文本位置。

**权重从高到低，分别是：**

1. 文本位置
2. 用户指定
3. locate
4. find

**Comment by erlinux** [comment]
肯定是要改的了，你们看我那样规划如何？

**Comment by lujun9972** [comment]
1和2互换一下位置吧

**Comment by erlinux** [comment]
okay

**Comment by erlinux** [comment]
已经解决，欢迎反馈。
