### ISSUE TITLE
重构讨论

### ISSUE THREAD

**Issue by vizv** [LCTT/lctt-cli#3]
请在这个 Issue 里谈谈你们对 LCTT 查询、申领、提交自动化脚本的想法。

当前任务：
1. ~~更改程序名为 lctt~~
2. 规范元数据格式，尽量做到可读而且代码容易改写
3. ~~规范 Usage 的格式~~
4. 创建 Bot 自动同意或拒绝申领的 PR，以及提供 API 调用等信息 [vizv/LCTT-Platform:lctt-bot](https://github.com/vizv/LCTT-Platform/tree/lctt-bot)
5. 在 Bot 中使用 GitHub 的 API 和 git 命令完成 fork、checkout 新分支、commit、push 到个人分支以及 PR 的工作

命令：
* init: 初始化文章仓库
* ~~list: 列出文章~~（需要修改）
* claim: 申领文章
* submit: 提交翻译
* ~~help: 显示帮助~~

提议（待讨论）：
无

**Comment by bestony** [comment]
lctt-helper已经有了，是个选题工具...

**Comment by vizv** [comment]
@bestony 可以集成进来

**Comment by bestony** [comment]
那个是图形化的。HTML 转md 工具

**Comment by vizv** [comment]
@bestony 可以通过命令行转换 md 的

**Comment by bestony** [comment]
@vizv 那就先做吧。好了再更名。
我更倾向图形化的。
具体要看o姐

**Comment by vizv** [comment]
@bestony 对，更名不重要，名字可以再讨论。现在代码里叫 lctt-helper

**Comment by vizv** [comment]
@bestony 我看 [LCTT/LCTT-Helper](https://github.com/LCTT/LCTT-Helper) 了，这个不太容易集成进来，不过我会想办法的（用 python 开个本地 HTTP 服务器应该就可以）。

**Comment by GOLinux** [comment]
先实现lctt的功能，再做一个search再说。

**Comment by vizv** [comment]
@GOLinux search 要实现什么呢？匹配关键字么？觉得如果只是申领的话关键字匹配不重要，而现在的工作重点是申领。

**Comment by chunyang-wen** [comment]
我觉得很多功能是不是可以使用Python来完成。毕竟Python在开发的上手和维护起来感觉都比较好。Python和Shell的交互也是没有问题的。

**Comment by vizv** [comment]
@chunyang-wen 是的，但是得有人开发……我不是 Python 的 fans（跟 ruby、Node.js 一样，开发个 cli 工具要很多外部的库，footprint 会很大）。当然你要是有想法可以接手这个项目 😃 。

**Comment by chunyang-wen** [comment]
@vizv 我先看一下这个cli的功能，然后看看难度吧。

**Comment by vizv** [comment]
你可以创建个 python 的分支，然后让用户选择用哪个。开源的生态环境嘛~

**Comment by chunyang-wen** [comment]
@vizv 这个可以有。

**Comment by erlinux** [comment]
当前已经完成“lctt-cli”生态体。关于PR部分暂时还不知道如何实现，这篇issue先关闭了。
