### ISSUE TITLE
example.cfg 注释错误

### ISSUE THREAD

**Issue by MjSeven** [LCTT/lctt-cli#36]
## example.cfg 注释错误
example.cfg 中写的是 `范本文件，应将其复制修改到 /tmp/lctt.cfg 便于程序读取`，当时当我复制并填写相关信息之后，`gn2` 命令依旧报错：
Online help: <https://github.com/lctt/lctt-cli>
2018-07-17 10:14:22 
	ERROR: Please SEE example.cfg File. 

我看了一下 `gn2.sh`，发现其读取的是 `/tmp/example.cfg`，于是我改变文件名之后，`gn2` 命令正常运行

### 修复
范本文件，应将其复制修改到 /tmp/example.cfg 便于程序读取

### 我们如何重现这个问题？
按照流程走一遍便会发现 `gn2` 并不能正常运行

### 环境
Ubuntu 16.04

**Comment by erlinux** [comment]
收到，正在重现问题

**Comment by erlinux** [comment]
**感谢！** 问题已得到修复，如发现其他问题可继续回复。

你可以通过以下操作得到更新：
```shell
cd /usr/local/lctt-cli
sudo git remote add lctt https://github.com/lctt/lctt-cli
sudo git pull lctt
```
